force-app/main/default/objects/Form_Creation2__c/Form_Creation2__c.object-meta.xml
<CustomObject>
    <label>Form Creator</label>
    <nameField>
        <displayFormat>form-{0}</displayFormat>
        <label>Formcreator</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form Creators</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_Creation2__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Africa</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>INDIA</fullName>
            </value>
            <value>
                <fullName>New zealand</fullName>
            </value>
            <value>
                <fullName>UK</fullName>
            </value>
            <value>
                <fullName>US</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Form_Creation2__c/fields/Experience__c.field-meta.xml
<CustomField>
    <fullName>Experience__c</fullName>
    <label>Experience</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form_Creation2__c/fields/Languages_Known__c.field-meta.xml
<CustomField>
    <fullName>Languages_Known__c</fullName>
    <label>Languages Known</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ANSI</fullName>
            </value>
            <value>
                <fullName>AWS</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>C++</fullName>
            </value>
            <value>
                <fullName>JAVA</fullName>
            </value>
            <value>
                <fullName>PYTHON</fullName>
            </value>
            <value>
                <fullName>RPA</fullName>
            </value>
            <value>
                <fullName>SALESFORCE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Form_Creation2__c/fields/Salary_Expected__c.field-meta.xml
<CustomField>
    <fullName>Salary_Expected__c</fullName>
    <externalId>true</externalId>
    <label>Salary Expected</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Form_Creation2__c/recordTypes/India.recordType-meta.xml
<RecordType>
    <fullName>India</fullName>
    <active>true</active>
    <label>India</label>
</RecordType>

force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/Referred_Teacher__c.field-meta.xml
<CustomField>
    <fullName>Referred_Teacher__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Referred Teacher</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Teacher__c.Name</field>
            <operation>contains</operation>
            <value>a</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Teacher__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Teacher__c/Teacher__c.object-meta.xml
<CustomObject>
    <label>Teacher</label>
    <nameField>
        <label>Teacher Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teachers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/DML_UPDATE.cls
public class DML_UPDATE {
    public static void updateRecord(){
        
        Form_Creation2__c formls = [Select First_Name__c,Country__c,Experience__c from Form_Creation2__c where first_name__c like '%pulihora gadu%'];
        formls.First_Name__c = 'Suri';
        Update formls;
       
            } 
    
    public static void bulkUpdate() {
         
        Form_Creation2__c[] formlist = [Select First_Name__c,Country__c,Experience__c from Form_Creation2__c where first_name__c like '%anvesh%' and Experience__c = '7'];
        List<Form_Creation2__c> tobeupdated = new List<Form_Creation2__c>();
        for( Form_Creation2__c formit : formlist ){
            formit.Country__c = 'US';
            tobeupdated.add(formit);
        }
        Update tobeupdated;
    } 
    
    public static void deleteRecords(){
        Form_Creation2__c[] formlist = [Select First_Name__c,Country__c,Experience__c from Form_Creation2__c where first_name__c like '%anvesh%' and Experience__c = '7'];
        Delete formlist;
    }
    
     public static void upsertRecords(){
         List<Form_Creation2__c> uprec = new List<Form_Creation2__c>{
            new Form_Creation2__c (First_Name__c='Anvesh',Country__c='INDIA',Experience__c='7',Languages_Known__c='RPA',Salary_Expected__c=50),
                 new Form_Creation2__c (First_Name__c='Anvesh',Country__c='UK',Experience__c='2',Languages_Known__c='AWS',Salary_Expected__c=700000)
                };
          Database.upsert(uprec,Form_Creation2__c.fields.Salary_Expected__c ,false) ;
             }
    
    Public static void relationshipStatus(){
       
      Sobject student =  [Select Name,Referred_Teacher__R.name from Student__c where name in ('Robert')];
       Sobject teacher = student.getSobject('Referred_Teacher__R.name');
       system.debug(teacher);
       
        
    }
}