force-app/main/default/objects/Form_Creation2__c/Form_Creation2__c.object-meta.xml
<CustomObject>
    <label>Form Creator</label>
    <nameField>
        <displayFormat>form-{0}</displayFormat>
        <label>Formcreator</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form Creators</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_Creation2__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Africa</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>INDIA</fullName>
            </value>
            <value>
                <fullName>New zealand</fullName>
            </value>
            <value>
                <fullName>UK</fullName>
            </value>
            <value>
                <fullName>US</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Form_Creation2__c/fields/Experience__c.field-meta.xml
<CustomField>
    <fullName>Experience__c</fullName>
    <label>Experience</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form_Creation2__c/fields/Languages_Known__c.field-meta.xml
<CustomField>
    <fullName>Languages_Known__c</fullName>
    <label>Languages Known</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ANSI</fullName>
            </value>
            <value>
                <fullName>AWS</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>C++</fullName>
            </value>
            <value>
                <fullName>JAVA</fullName>
            </value>
            <value>
                <fullName>PYTHON</fullName>
            </value>
            <value>
                <fullName>RPA</fullName>
            </value>
            <value>
                <fullName>SALESFORCE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Form_Creation2__c/fields/Salary_Expected__c.field-meta.xml
<CustomField>
    <fullName>Salary_Expected__c</fullName>
    <externalId>true</externalId>
    <label>Salary Expected</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Form_Creation2__c/recordTypes/India.recordType-meta.xml
<RecordType>
    <fullName>India</fullName>
    <active>true</active>
    <label>India</label>
</RecordType>

force-app/main/default/classes/FirstClassOnDML.cls
public class FirstClassOnDML {

    public static Void insertRecord() {      
        Form_Creation2__c fc = new Form_Creation2__c(
        First_Name__c='Anvesh',Country__c='UK',Experience__c='2',Languages_Known__c='AWS',Salary_Expected__c=700000);
        Insert fc;
        ID fcid = fc.Id;
        System.debug(fcid);     
    }
    
    public static void BulkInsert(){
        
        List<Form_Creation2__c> fc = new List<Form_Creation2__c>{
		new Form_Creation2__c(First_Name__c='anvesh',Country__c='UK',Experience__c='7',Languages_Known__c='AWS',Salary_Expected__c=700000),
        new Form_Creation2__c(First_Name__c='vempi',Country__c='Africa',Experience__c='5',Languages_Known__c='ANSI',Salary_Expected__c=800000),
        new Form_Creation2__c(First_Name__c='pogula',Country__c='Germany',Experience__c='4',Languages_Known__c='RPA',Salary_Expected__c=900000),
		new Form_Creation2__c(First_Name__c='reddy',Country__c='INDIA',Experience__c='4',Languages_Known__c='PYTHON',Salary_Expected__c=1000000)            
        };
            List<id> obid = new List<id>();
        for(Form_Creation2__c fnew : fc){
            if(fnew.Id !=  null){
            obid.add(fnew.Id+'  '+fnew.Country__c);
            }
                }
        for(id qa : obid){
            system.debug(qa);
        }
      Database.SaveResult[] res =Database.insert(fc,false);
        
        for(Database.SaveResult sr : res){
            if( sr.isSuccess()){
                system.debug('Record created successfully with id = '+sr.id);
            }
            else{
                for(Database.Error er :  sr.getErrors()){
							                 
                    system.debug('Error Message is = '+er.getMessage()+'And Error code is ='+er.getStatusCode());
                     System.debug('fields that affected this error: ' + er.getFields());
                }
                
            } 
        }
    }
}